server:
  port: 8079

spring:
  application:
    name: ads-infra

  datasource:
    url: jdbc:mysql://localhost:3390/security
    username: sec_user
    password: psw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
